runtime: python39

env: standard

entrypoint: python backend/main.py

automatic_scaling:
  min_idle_instances: 0 # idle状態にあるインスタンスの最小値
  max_idle_instances: 1 # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic
