version: 2.1
orbs:
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2 # nodeのバージョンは開発環境に合わせる

    working_directory: ~/repo # 作業フォルダ

    steps:
      - checkout # プロジェクトに追加したGitHubリポジトリをworking_directoryにcloneしてcheckout

      # キャッシュがある場合はキャッシュから依存関係を復元
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/packages-lock.json" }}
            - v1-dependencies-

      # 依存関係のインストール
      - run:
          working_directory: frontend
          name: Install dependencies # CircleCI上で表示される処理名(任意)
          command: npm ci # 処理コマンド

      # ビルド
      - run:
          working_directory: frontend
          name: Build
          command: npm run build

      # ビルドの確認
      - run:
          working_directory: frontend
          name: Check dist
          command: ls -la dist

      # キャッシュの保存
      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
          key: v1-dependencies-{{ checksum "frontend/package-lock.json" }}
  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo # 作業フォルダ

    steps:
      - checkout # プロジェクトに追加したGitHubリポジトリをworking_directoryにcloneしてcheckout

      # キャッシュがある場合はキャッシュから依存関係を復元
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/package-lock.json" }}
            - v1-dependencies-
      - run:
          working_directory: backend
          name: deploy
          command: gloud app deploy

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy
          requires:
            - build
