version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  build:
    docker:
      - image: cimg/node:16.14.2 # nodeのバージョンは開発環境に合わせる

    working_directory: ~/repo # 作業フォルダ

    steps:
      - checkout # プロジェクトに追加したGitHubリポジトリをworking_directoryにcloneしてcheckout

      # キャッシュがある場合はキャッシュから依存関係を復元
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/package-lock.json" }}
            - v1-dependencies-

      # 依存関係のインストール
      - run:
          working_directory: frontend
          name: Install dependencies # CircleCI上で表示される処理名(任意)
          command: npm ci # 処理コマンド

      # ビルド
      - run:
          working_directory: frontend
          name: Build
          command: npm run build

      # ビルドの確認
      - run:
          working_directory: frontend
          name: Check dist
          command: ls -la dist

      # キャッシュの保存
      - save_cache:
          paths:
            - node_modules
            - dist
            - package.json
          key: v1-dependencies-{{ checksum "frontend/package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/node:16.14.2

    working_directory: ~/repo # 作業フォルダ
    executor: gcp-cli/default
    steps:
      - attach_workspace:
          at: .
      - gcp-cli/install
      - gcp-cli/initialize
      - run:
          name: deploy
          command: gcloud app deploy

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
